search_radius: "1.0"
min_price: "350000"
max_price: "550000"
min_bedrooms: "1"
max_bedrooms: "3"
postcodes: {
  22: "NW117RN",
  23: "NW101NU",
  24: "NW53AF",
  25: "NW36LU",
  26: "NW34TG",
  27: "N193TX",
  28: "N20PE",
}