name: Test clean data
on:
  workflow_dispatch:

env: 
  SEARCH_AREA: "all postcodes"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: get_date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Checking out repo
        uses: actions/checkout@v3
        
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Installing package list
        run: apt list --installed    

      - name: Install tesseract
        run: |
         sudo apt-get update
         sudo apt-get install libleptonica-dev tesseract-ocr tesseract-ocr-dev libtesseract-dev python3-pil tesseract-ocr-eng tesseract-ocr-script-latn
    

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running the Python script
        run: |
          python src/clean_data.py -s "${{ env.SEARCH_AREA }}" -p "github"
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Testing clean_data.py"
          git push
