name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
        
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Installing package list
        run: apt list --installed    
        
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable
        
      - name: Create Extension Directory
        run: mkdir -p /home/runner/work/London-House-Prices/chrome_extension_zip
             mkdir -p /home/runner/work/London-House-Prices/chrome_extension
        
      - name: Download Chrome Extension
        run: |
          # Define download and unzip paths
          DOWNLOAD_PATH="/home/runner/work/London-House-Prices/chrome_extension_zip/extension.zip"
          UNZIP_PATH="/home/runner/work/London-House-Prices/chrome_extension"
          # Download the Chrome extension from the Chrome Web Store URL
          wget -O "$DOWNLOAD_PATH" "https://chrome.google.com/webstore/detail/property-log/jccihedpilhidcbkconacnalppdeecno"
  
          # Unzip the extension (you may need to adjust this depending on the extension)
          unzip "$DOWNLOAD_PATH" -d "$EXTRACT_PATH"
  
          # Move the extension to a location accessible to your Selenium script
          # mv extension /home/runner/work/London-House-Prices/chrome_extension
        
       # Need to fetch reqs if needed
      # - name: Installing all necessary packages
      #   run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      # - name: Install xvfb
      #   run: sudo apt-get install xvfb
      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Running the Python script
      #   run: python test_house_scraper.py
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Testing selenium in GH actions"
          git push
